### ISSUE TITLE
Window Border has Wrong Color

### ISSUE THREAD

**Issue by atlastodor** [ControlzEx/ControlzEx#47] opened 2018-04-03 10:19 UTC
The window border (on Windows 10 and probably on other versions) has a wrong color. This is visible on the illustration below. Wrong color (left) and default color (right).
![windowborder](https://user-images.githubusercontent.com/22751987/38243137-de13bd26-3736-11e8-974d-a892c89980ed.png)

Some debugging shows that you use DwmExtendFrameIntoClientArea for the border. For this to work correctly, the area under the border must be painted black (poorly documented in https://msdn.microsoft.com/en-us/library/windows/desktop/bb688195(v=vs.85).aspx). But you use the border brush, which makes the shaders produce strange results. This is especially visible with non-standard border colors, for example #FF2B579A or the FluentRibbon sample. Setting the border color to black produces the default bluish border color taken from the Windows style.

To make things worse, there appears to be a bug in the RDP implementation. Using the above technique with WinForms works correctly. But when the app is written in WPF and the users connects remotely via RDP (Remote Desktop), I guess that the DirectX surface is somehow transferred differently and the  DwmExtendFrameIntoClientArea does not work and produces a black border (the effective border color). I've written two simple test apps to verify this and WinForm works but not WPF. Those contain very few lines of almost identical code (let me know if you want them).

To work around the above mentioned issue, I change the border color depending on the session type (local or remote). I also listen for changes and change the border color on the fly, when the session type changes (black for local sessions, bluish for remote sessions). Listen to events from Microsoft.Win32.SystemEvents.SessionSwitch and test for GetSystemMetrics(SM_REMOTESESSION).

This works for us, because our app has a bluish color scheme and there is not much difference between the default Windows border color and our bluish color (users won't notice it). However, if the app has a different color, some other tricks are needed. Some googling hinted DwmSetColorizationParameters, but this is undocumented. Since this is no priority for us, I did not investigate.

**Comment by batzen** [comment] 2018-04-07 17:12
On which windows version did you reproduce the border color issue?
I can't reproduce this behavior on Windows 10 1709.

Would be nice if you could provide your test apps.

**Comment by atlastodor** [comment] 2018-04-07 18:58
Hi Bastian,

On Microsoft Windows [Version 10.0.16299.309].

I've attached the test app. Two apps, one WinForms and one WPF. Very simple both of them. Try them both and both locally and via RDP. The WPF one behaves differently.

In the WPF app, you will need to click on the button to set the glass border. You can also type new border color on the fly - to experiment.
[GlassFrame.zip](https://github.com/ControlzEx/ControlzEx/files/1886643/GlassFrame.zip)

**Comment by batzen** [comment] 2018-04-16 16:59
I will try to port the Glow from MahApps.Metro to ControlzEx.
That should eliminate the resize border problem.

And it's the same technique which is used in visual studio.

@punker76 What do you think about that?

**Comment by batzen** [comment] 2018-07-06 18:57
Behavior is now ported here and will be used in Fluent.Ribbon. Closing this.

**Closed by batzen** 2018-07-06 18:57 UTC
Labels: Feature
