### ISSUE TITLE
Error found when trying to target this app to .net5

### ISSUE THREAD

**Issue by jiangzeng01** [ControlzEx/ControlzEx#136] opened 2020-09-10 07:05 UTC
Hi,

I'm trying to retarget 3.x apps to .net 5 and try to build to see if it works fine.
Opening the ticket to track the issues when targeting .net 5.

The app works fine with the default target.
We are trying to target this app to .net5, SDK used: 5.0.100-rc.1.20454.5.

It fails to build, see errors in error file:
[errors when target .net5.txt](https://github.com/ControlzEx/ControlzEx/files/5199731/errors.when.target.net5.txt)

**Comment by batzen** [comment] 2020-09-10 08:41
That's caused by a changed default behavior regarding compiler warnings in .NET 5.
Will have a look at this.

**Comment by batzen** [comment] 2020-10-03 21:15
Those errors are fixed in https://github.com/ControlzEx/ControlzEx/pull/125

**Closed by batzen** 2020-10-03 21:15 UTC
Labels: Bug

**Comment by jiangzeng01** [comment] 2020-10-09 00:57
@batzen Thanks for the fix!
