### ISSUE TITLE
Opening a window will in some cases lead to a crash

### ISSUE THREAD

**Issue by cbra-caa** [ControlzEx/ControlzEx#115] opened 2020-05-18 13:08 UTC
After updating to version 4.2.2 I've been sporadically seeing some users report the following error. I haven't been able to reproduce it locally, or for the user.

Initially I got it mixed up with the https://github.com/ControlzEx/ControlzEx/issues/103 but this one still persists after the fix.

Catching Unhandled exception:System.ComponentModel.Win32Exception (0x80004005): 
   at ControlzEx.Behaviors.GlowWindowBehavior.UpdateZOrderOfOwner(IntPtr hwndOwner)
   at ControlzEx.Behaviors.GlowWindowBehavior.UpdateZOrderOfThisAndOwner()
   at ControlzEx.Behaviors.GlowWindowBehavior.AssociatedObjectWindowProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by batzen** [comment] 2020-05-20 21:49
There seems to be one stack frame missing.
There should be a call to some method in `NativeMethods`.
A stacktrace with line numbers would also help in this case.
There is not much code inside `UpdateZOrderOfOwner` but i don't know which part should cause an issue here.
Doe you have any description of what was done in your application during the crash?

**Comment by cbra-caa** [comment] 2020-05-22 09:21
All three cases I have on record are thrown on this stacktrace

> LOGGER: Unhandled exception:
> System.ComponentModel.Win32Exception (0x80004005): Forkert parameter
>    ved ControlzEx.Behaviors.GlowWindowBehavior.UpdateZOrderOfOwner(IntPtr hwndOwner)
>    ved ControlzEx.Behaviors.GlowWindowBehavior.UpdateZOrderOfThisAndOwner()
>    ved ControlzEx.Behaviors.GlowWindowBehavior.AssociatedObjectWindowProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    ved System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    ved MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    ved MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
>    ved System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    ved System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

All cases occured on a user either opening or closing a window. In addition all calls were made on the main thread, and the application itself was not in a state of shutting down, so the closing window was not the main window of the application.

Dispatcher: HasShutdownFinished=False, HasShutdownStarted=False
Dispatcher.Thread: ManagedThreadId=1, Name=Main, ThreadState=Running, IsAlive=True, IsBackground=False

Currently I dont have any stacktraces with line numbers - I'll see if I can get the into the next build.

The error is very elusive though, so I have no real perception of when its going to happen again.

**Comment by batzen** [comment] 2020-07-25 17:17
This should have been fixed by #127

**Closed by batzen** 2020-07-25 17:17 UTC

**Comment by webprofusion-chrisc** [comment] 2021-06-09 02:40
Sorry to re-open this but my app allows users to submit crash reports and we're occasionally seeing the following. I have been unable to reproduce it myself but I assume that the check for a valid window handle is returning false information (i.e. the window is perhaps already being destroyed or is not yet fully created or is owned by another thread?):

```cs
System.ArgumentException: E_INVALIDARG
 at ControlzEx.Standard.HRESULT.ThrowIfFailed(String message)
 at ControlzEx.Standard.HRESULT.ThrowLastError()
 at ControlzEx.Standard.NativeMethods.SetWindowPos(IntPtr hWnd, IntPtr hWndInsertAfter, Int32 X, Int32 Y, Int32 cx, Int32 cy, SWP uFlags)
 at ControlzEx.Behaviors.GlowWindowBehavior.UpdateZOrderOfOwner(IntPtr hwndWindow, IntPtr hwndOwner)
 at ControlzEx.Behaviors.GlowWindowBehavior.UpdateZOrderOfThisAndOwner()
 at ControlzEx.Behaviors.GlowWindowBehavior.AssociatedObjectWindowProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
 at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
 at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
 at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
 at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
 at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
 at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
 at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
```

The app is using MahApps Metro 2.4.5.4 which in turn uses ControlzEx 4.4.0.50

**Comment by batzen** [comment] 2021-06-14 16:51
@webprofusion-chrisc These kinds of issues should be completely gone with ControlzEx 6.0 which will contain a completely rewritten GlowWindow.

**Comment by webprofusion-chrisc** [comment] 2021-06-15 01:52
@batzen thanks!

**Comment by anakrivokuca** [comment] 2021-08-05 09:47
We are experiencing the same issue. It seems to be reproducible in some specific cases after closing an application window that is not main window. For one case it only happens while having the main application window minimized in system tray. The exception we are getting is:
```
Exception: System.ArgumentException: E_INVALIDARG
   at ControlzEx.Standard.HRESULT.ThrowIfFailed(String message)
   at ControlzEx.Standard.HRESULT.ThrowLastError()
   at ControlzEx.Standard.NativeMethods.SetWindowPos(IntPtr hWnd, IntPtr hWndInsertAfter, Int32 X, Int32 Y, Int32 cx, Int32 cy, SWP uFlags)
   at ControlzEx.Behaviors.GlowWindowBehavior.UpdateZOrderOfOwner(IntPtr hwndWindow, IntPtr hwndOwner)
   at ControlzEx.Behaviors.GlowWindowBehavior.UpdateZOrderOfThisAndOwner()
   at ControlzEx.Behaviors.GlowWindowBehavior.AssociatedObjectWindowProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

This started happening after upgrading ControlzEx from 3.0.2 to 5.0.0.30 version. We have also updated MahApps.Metro library to 2.4.5.4 and Catel to 5.12.16. 
We are not able to wait for ControlzEx 6.0.0.0 version. Do you maybe have any idea, proposal how to avoid this exception?
Is there any open ticket for this issue or should we have this one reopened? 
Thank you
